version: "3.7"
services:
  frontend:
    build:
      context: docker/nginx
    restart: always
    expose:
      - 80
    volumes:
      - ./public:/app
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}