name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Copy repository
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.STAKECRM_HOST }}
          USERNAME: ${{ secrets.STAKECRM_USERNAME }}
          PORT: ${{ secrets.STAKECRM_PORT }}
          KEY: ${{ secrets.STAKECRM_SSHKEY }}
        with:
          debug: false
          host: ${{ secrets.STAKECRM_HOST }}
          username: ${{ secrets.STAKECRM_USERNAME }}
          port: ${{ secrets.STAKECRM_PORT }}
          key: ${{ secrets.STAKECRM_SSHKEY }}
          source: '.,!.git'
          target: '/home/admin/slavapakeev.ru'

      - name: Migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAKECRM_HOST }}
          username: ${{ secrets.STAKECRM_USERNAME }}
          port: ${{ secrets.STAKECRM_PORT }}
          key: ${{ secrets.STAKECRM_SSHKEY }}
          script: |
            cd slavapakeev.ru
            docker-compose up -d --build
